language: objective-c
script: xctool -workspace HelloMixpanel/HelloMixpanel.xcworkspace -scheme HelloMixpanel
  -sdk iphonesimulator8.0 -destination platform='iOS Simulator',OS=8.0,name='iPhone
  6' ONLY_ACTIVE_ARCH=NO clean test
env:
  global:
  - APP_NAME="HelloMixpanel"
  - 'DEVELOPER_NAME="iPhone Distribution: Mixpanel, Inc."'
  - PROFILE_NAME="HelloMixpanel_Ad_Hoc"
  - secure: VH/1fxfVjjUn5imsV+lWJguVbRmhSuTd3k3RzgA/WJWfGTXgPTSsYWfljQQ7vDOgY4I7pRWjMW9ezcpMchuBkACI7ihO+N2dN5iCXfzJFmBOSZkJuKC4SPWkCphXsVLCPLBgkYi3P6ovPIM+shykFdsz0YusZMX8eBXJV02F1ic=
before_install:
- brew update
- brew upgrade xctool
install: (gem update cocoapods && cd HelloMixpanel/ ; pod install)
before_script:
- xctool --version
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/HelloMixpanel_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/HelloMixpanel_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
